import * as vscode from 'vscode';
// Original by KevinVG207
// Uma-Carotene-TL/src/ui/common.py
const categories: Record<string, string> = {
    "1":  vscode.l10n.t('Error Descriptions'),
    "2":  vscode.l10n.t('Errors'),
    "3":  vscode.l10n.t('Tutorial'),
    "4":  vscode.l10n.t('Outfit+Chara Combo'),
    "5":  vscode.l10n.t('Outfit Titles'),
    "6":  vscode.l10n.t('Character Names'),
    "7":  vscode.l10n.t('Voice Actors'),
    "8":  vscode.l10n.t('Profile Residence'),
    "9":  vscode.l10n.t('Profile Weight'),
    "10": vscode.l10n.t('Item Descriptions (Long Tap)'),
    "13": vscode.l10n.t('Gacha Descriptions'),
    "14": vscode.l10n.t('Clothes'),
    "15": vscode.l10n.t('Clothes Caption(?)'),
    "16": vscode.l10n.t('Song Names'),
    "17": vscode.l10n.t('Song Credits'),
    "23": vscode.l10n.t('Item Names'),
    "24": vscode.l10n.t('Item Descriptions'),
    "25": vscode.l10n.t('How to obtain items'),
    "26": vscode.l10n.t('Gacha Banners'),
    "27": vscode.l10n.t('?'),
    "28": vscode.l10n.t('Race Names (Long)'),
    "29": vscode.l10n.t('Race Names (Short)'),
    "31": vscode.l10n.t('Race Course Names'),
    "32": vscode.l10n.t('Race Names'),
    "33": vscode.l10n.t('Race Names'),
    "34": vscode.l10n.t('Race Course Names'),
    "35": vscode.l10n.t('Race City Names'),
    "36": vscode.l10n.t('Race Names'),
    "38": vscode.l10n.t('Race Names (Short)'),
    "39": vscode.l10n.t('Item Names 2'),
    "40": vscode.l10n.t('? Shop Descriptions'),
    "41": vscode.l10n.t('Item exchange conditions'),
    "42": vscode.l10n.t('Jewel Amounts'),
    "47": vscode.l10n.t('Skill Names'),
    "48": vscode.l10n.t('Skill Descriptions'),
    "49": vscode.l10n.t('Jewel Amounts'),
    "55": vscode.l10n.t('Training/Outing Types'),
    "59": vscode.l10n.t('Mob Uma Names'),
    "63": vscode.l10n.t('?'),
    "64": vscode.l10n.t('Reward Descriptions'),
    "65": vscode.l10n.t('Titles'),
    "66": vscode.l10n.t('Title Descriptions'),
    "67": vscode.l10n.t('Missions'),
    "68": vscode.l10n.t('Loading Screen Headers'),
    "69": vscode.l10n.t('Secrets/Tips/Comics'),
    "70": vscode.l10n.t('Login Bonus'),
    "75": vscode.l10n.t('Support+Chara Combo'),
    "76": vscode.l10n.t('Support Card Titles'),
    "77": vscode.l10n.t('Character Names'),
    "78": vscode.l10n.t('Character Names (No Kanji)'),
    "88": vscode.l10n.t('Card Stories'),
    "92": vscode.l10n.t('Character Story Chapters'),
    "94": vscode.l10n.t('Main Story Chapters'),
    "113": vscode.l10n.t('Chara Pieces'),
    "119": vscode.l10n.t('Scenario Names'),
    "120": vscode.l10n.t('Scenario Descriptions'),
    "144": vscode.l10n.t('Profile Slogan'),
    "147": vscode.l10n.t('Factors(?)'),
    "151": vscode.l10n.t('Support Events'),
    "157": vscode.l10n.t('Profile Birthday'),
    "158": vscode.l10n.t('Profile Height'),
    "162": vscode.l10n.t('Profile Grade'),
    "163": vscode.l10n.t('Profile Descriptions'),
    "164": vscode.l10n.t('Profile Strengths'),
    "165": vscode.l10n.t('Profile Weaknesses'),
    "166": vscode.l10n.t('Profile Ears'),
    "167": vscode.l10n.t('Profile Tail'),
    "168": vscode.l10n.t('Profile Shoe Size'),
    "169": vscode.l10n.t('Profile Family'),
    "170": vscode.l10n.t('Character Names'),
    "172": vscode.l10n.t('Factor details'),
    "173": vscode.l10n.t('NPC Job Title'),
    "181": vscode.l10n.t('Training Event Titles'),
    "182": vscode.l10n.t('Chara Names (katakana)'),
    "189": vscode.l10n.t('Story Event Titles'),
    "191": vscode.l10n.t('Story Event Chapters'),
    "214": vscode.l10n.t('Story Event Titles (Short)'),
    "222": vscode.l10n.t('Anniv. Story Chapters')
};
export default categories;