// Original by KevinVG207
// Uma-Carotene-TL/src/ui/common.py
const categories: {[key: string]: string} = {
    "1": "> Errors Description",
    "2": "> Errors",
    "3": "> Tutorials",
    "4": "> Characters [Outfit]Name",
    "5": "> Characters Outfit Titles",
    "6": "> Characters Names",
    "7": "> VA Names",
    "8": "> Profile Residence",
    "9": "> Profile Weight",
    "10": "> Items Description (Hold)",
    "13": "> Gacha Descriptions",
    "14": "> Outfit Names",
    "15": "> Outfit Descriptions",
    "16": "> Song Titles",
    "17": "> Song Credits",
    "23": "> Item Names",
    "24": "> Item Descriptions",
    "25": "> How to Obtain Items",
    "26": "> Gacha Banners",
    "27": "> Tazuna Career Predictions",
    "28": "> Race Names #1 (Long)",
    "29": "> Race Names #2 (Short)",
    "31": "> Racecourse Names #1",
    "32": "> Race Names #3",
    "33": "> Race Names #4",
    "34": "> Racecourse Names #2",
    "35": "> Race City Names",
    "36": "> Race Names #5",
    "38": "> Race Names #6 (Short)",
    "39": "> Shop Promotions",
    "40": "> Shop Promo Descriptions",
    "41": "> Item Exchange Conditions",
    "42": "> Shop Jewels",
    "47": "> Skills Names",
    "48": "> Skills Description",
    "49": "> Jewel Amounts",
    "55": "> Training/Outing Types",
    "59": "> Umamusume Mob Names",
    "63": "> Player Help Button",
    "64": "> Reward Descriptions",
    "65": "> Titles",
    "66": "> Title Descriptions",
    "67": "> Missions",
    "68": "> Secrets Headers",
    "69": "> Secrets Tips/Comics",
    "70": "> Login Bonus",
    "75": "> Support Card [Title]Name",
    "76": "> Support Card [Title]",
    "77": "> Support Card Names",
    "78": "> Support Card Names (No Kanji)",
    "88": "> Support Card Stories",
    "91": "> Main Story Arcs",
    "92": "> Umamusume Story Episodes",
    "93": "> Main Story Chapter Texts",
    "94": "> Main Story Episode Names",
    "95": "> Main Story Umamusume Names",
    "96": "> Main Story Episode Texts",
    "97": "> Tazuna Career Tips",
    "111": "> Graded Race Names",
    "112": "> Main Story Chapters",
    "113": "> Star Pieces",
    "114": "> Star Pieces Description",
    "119": "> Playable Scenario Names",
    "120": "> Playable Scenario Intros",
    "121": "> Umamusume Classes",
    "128": "> Jukebox Song Descriptions",
    "130": "> Honor Titles",
    "131": "> Honor Titles Requirements",
    "133": "> Items",
    "136": "> Chat Related Texts",
    "138": "> Career Training Names",
    "139": "> Career Reporter Otonashi Text (?)",
    "140": "> Race History Info #1",
    "141": "> Race History Info #2",
    "142": "> Career Conditions",
    "143": "> Career Condition Descriptions",
    "144": "> Profile (About)",
    "147": "> Sparks Names",
    "148": "> Team Stadium Bonuses",
    "150": "> Support Card Unique Perk Names",
    "151": "> Support Card Effects",
    "152": "> NPC Names #1",
    "154": "> Support Card Effect Descriptions",
    "155": "> Support Card Unique Perk Effects",
    "157": "> Profile Birthdays",
    "158": "> Profile Height",
    "159": "> Race Strategies",
    "160": "> Race Tracks",
    "161": "> Race Distances",
    "162": "> Profile Grade",
    "163": "> Profile Description",
    "164": "> Profile Strengths",
    "165": "> Profile Weaknesses",
    "166": "> Profile Ears",
    "167": "> Profile Tail",
    "168": "> Profile Shoe Size",
    "169": "> Profile Family",
    "170": "> Umamusume Names #3",
    "171": "> Random Events Requirements",
    "172": "> Sparks Details",
    "173": "> NPC Job Title",
    "174": "> Aoharu Scenario Characters",
    "175": "> Profile Categories",
    "176": "> Shop Recovery Items #1",
    "177": "> Career Raffle Items",
    "178": "> Career Random Items #1",
    "179": "> Career Random Items #2",
    "180": "> Career Random Items #3",
    "181": "> Training Events",
    "182": "> Character Names (Katakana)",
    "184": "> Push Notifications (TP)",
    "185": "> Push Notifications (RP)",
    "187": "> Campaign Names",
    "188": "> Campaign Descriptions",
    "189": "> Story Event Names",
    "190": "> Story Event Missions",
    "191": "> Story Event Episodes",
    "192": "> Places #2",
    "193": "> Aoharu Scenario #1",
    "194": "> Aoharu Scenario #2",
    "195": "> Aoharu Scenario #3",
    "196": "> Event Notices Board",
    "197": "> Shop Recovery Items #2",
    "198": "> Scenario Bonus Texts #1",
    "199": "> Scenario Bonus Texts #2",
    "200": "> Scenario Bonus Texts #3",
    "201": "> Monthly Twinkle #1",
    "202": "> Monthly Twinkle #2",
    "203": "> Monthly Twinkle #3",
    "204": "> Monthly Twinkle #4",
    "205": "> Monthly Twinkle #5",
    "206": "> Champions Meeting Cups",
    "207": "> Grand Concert Scenario #1",
    "208": "> Grand Concert Scenario #2",
    "209": "> Grand Concert Scenario #3",
    "210": "> Grand Concert Scenario #4",
    "211": "> Story Event Announcements",
    "212": "> Obsolete Story Event Announcement",
    "214": "> Story Event Titles (Short)",
    "215": "> Special Transfers #1",
    "216": "> Special Transfers #2",
    "217": "> Special Transfers #3",
    "218": "> Aoharu Scenario #4",
    "220": "> Special Transfers #4",
    "221": "> Anniv. Texts",
    "222": "> Anniversary Story Chapters",
    "223": "> Places #1",
    "225": "> Climax Scenario #1",
    "226": "> Climax Scenario #2",
    "227": "> Climax Scenario #3 (?)",
    "228": "> Uma Jukebox Character Text",
    "229": "> Champions Meeting Race Text #1 (?)",
    "230": "> Champions Meeting Race Text #2",
    "231": "> Interview Questions",
    "232": "> Interview Answers",
    "233": "> Golshi-chan Mode",
    "234": "> Kirari Related (?)",
    "235": "> Kirari Related (?) #1",
    "236": "> Kirari Related (?) #2",
    "237": "> Scenario Names (Short)",
    "238": "> Climax Scenario #4",
    "239": "> Kirari Related (?) #3",
    "240": "> All Scenario Texts",
    "241": "> Racing Carnival",
    "242": "> Racing Carnival #1",
    "243": "> Race History Info #3",
    "244": "> Race History Info #4",
    "245": "> Racing Carnival #2",
    "246": "> Kirari Related (?) #4",
    "247": "> Grand Concert Titles",
    "248": "> Grand Concert Scenario #5",
    "249": "> Grand Concert Title Requirements",
    "250": "> Grand Concert Scenario #6",
    "251": "> Grand Concert Scenario #7",
    "252": "> Concert Teather Requirements (?)",
    "253": "> (?)",
    "254": "> Golshi-chan Mode (?) #1",
    "255": "> Golshi-chan Mode (?) #2",
    "256": "> Golshi-chan Mode (?) #3",
    "257": "> Racing Carnival (?) #3",
    "258": "> Profile Habits",
    "259": "> Profile Hidden Skill",
    "260": "> Profile Often Buys",
    "261": "> (?)",
    "262": "> (?)",
    "263": "> (?)",
    "264": "> NPC Names #2",
    "265": "> Strive! Ultimate Team",
    "266": "> Streams & PakaLive Info",
    "267": "> Career Critical Choices",
    "268": "> Stroll Locations",
    "269": "> YouTube Redirect Texts",
    "270": "> Grand Concert Scenario #8",
    "271": "> Valentine's Day Choco Messages #1",
    "272": "> Valentine's Day Choco Messages #2",
    "273": "> Valentine's Day Choco Names",
    "274": "> League of Heroes",
    "275": "> League of Heroes Chart Texts",
    "276": "> IRL Live Performances Texts",
    "277": "> IRL Live Game Gacha Tickets",
    "278": "> NPC Names #3",
    "279": "> Obsolete Event Text Schedule #2",
    "280": "> Obsolete Christmas Text (?)",
    "281": "> Obsolete Event Text Schedule #1",
    "282": "> Kirari Event Text #1",
    "283": "> Anniversary Event Text #1",
    "284": "> Kirari Event Text #2",
    "285": "> Anniversary Event Text #2",
    "286": "> Kirari Event Text #3",
    "287": "> Campaign Page Text",
    "288": "> Event Schedule Text",
    "289": "> Kirari Event Schedule Text",
    "290": "> Skill Evolution Challenges",
    "293": "> (?)",
    "294": "> Goddesses Scenario #1",
    "295": "> Goddesses Scenario #2",
    "296": "> Goddesses Scenario #3",
    "297": "> League of Heroes Tazuna Text",
    "298": "> Goddesses Scenario #4",
    "299": "> Goddesses Scenario #5",
    "300": "> Goddesses Scenario #6",
    "301": "> Tachyon Research Event",
    "302": "> Sakura Stroll Event",
    "303": "> Sakura Stroll Event #1",
    "304": "> Sakura Stroll Event #2",
    "305": "> Sakura Stroll Event #3",
    "306": "> Sakura Stroll Event #4",
    "307": "> Sakura Stroll Event #5",
    "308": "> Sakura Stroll Event #6",
    "309": "> Sakura Stroll Event #7",
    "310": "> L'Arc Scenario #1",
    "311": "> L'Arc Scenario #2",
    "312": "> Sakura Stroll Event #8",
    "313": "> L'Arc Scenario #3",
    "314": "> L'Arc Scenario #4",
    "315": "> L'Arc Scenario #5",
    "316": "> L'Arc Scenario #6",
    "317": "> L'Arc Scenario #7",
    "318": "> L'Arc Scenario #8",
    "319": "> Special Transfers #5",
    "320": "> Special Transfers #6",
    "321": "> Special Transfers #7",
    "322": "> L'Arc Scenario #9",
    "323": "> U.A.F. Scenario #1",
    "325": "> Event Prologues",
    "326": "> L'Arc Scenario #10",
    "327": "> Special Shop Tickets",
    "328": "> U.A.F. Scenario #2",
    "329": "> U.A.F. Scenario #3",
    "330": "> U.A.F. Scenario #4",
    "331": "> Food Festival Scenario #1",
    "332": "> Food Festival Scenario #2",
    "333": "> Food Festival Scenario #3",
    "334": "> Food Festival Scenario #4",
    "336": "> Food Festival Scenario #5",
    "337": "> U.A.F. Scenario #5",
    "338": "> Mecha-Uma Scenario #1",
    "339": "> Mecha-Uma Scenario #2",
    "340": "> Mecha-Uma Scenario #3",
    "342": "> Mecha-Uma Scenario #4",
    "343": "> Mecha-Uma Scenario #5",
    "344": "> Mecha-Uma Scenario #6",
    "345": "> U.A.F. Scenario #6",
    "346": "> Food Festival Scenario #6",
    "347": "> U.A.F. Scenario #7",
    "348": "> Food Festival Scenario #7",
    "349": "> Food Festival Scenario #8",
    "350": "> Anniv. (?)",
    "351": "> U.A.F. Scenario #8",
    "352": "> (?)",
    "353": "> Food Festival Scenario #9",
    "354": "> Food Festival Scenario #10",
    "355": "> Anniv. Related #1",
    "356": "> Anniv. Related #2",
    "357": "> Locations (Jobs)",
    "358": "> Food Festival Scenario #11",
    "359": "> Food Festival Scenario #12",
    "360": "> Push Notifications (Jobs)",
    "361": "> Food Festival Scenario #13",
    "362": "> Description Texts (Jobs)",
    "363": "> Legends Scenario #1",
    "364": "> Legends Scenario #2",
    "365": "> Half Anniv. Event #1",
    "366": "> Half Anniv. Event #2",
    "367": "> Half Anniv. Event #3",
    "368": "> Half Anniv. Event #4",
    "369": "> Legends Scenario #3",
    "370": "> Legends Scenario #4",
    "371": "> Legends Scenario #5",
    "372": "> Umamusume Names #4 (English)",
    "373": "> Santa Anita Park Names",
    "374": "> Island Scenario #1",
    "375": "> Island Scenario #2",
    "376": "> Umamusume Names #5 (Short)",
    "377": "> Subscription Texts #1",
    "378": "> Subscription Texts #2",
    "379": "> Subscription Texts #3",
    "380": "> Subscription Texts #4",
    "381": "> Subscription Texts #5",
    "382": "> Subscription Texts #6",
    "383": "> Island Scenario #3",
    "385": "> Legends Scenario #6",
    "386": "> Rental Decks",
    "387": "> Autoplay #1",
    "388": "> Autoplay #2",
    "389": "> Autoplay #3",
    "390": "> Autoplay #4",
    "391": "> Autoplay #5",
    "392": "> Autoplay #6",
    "393": "> Autoplay #7",
    "394": "> Outcomes Button",
    "397": "> Onsen Scenario #1",
    "398": "> Onsen Scenario #2",
    "399": "> Onsen Scenario #3",
    "400": "> Island Scenario #4",
    "401": "> Autoplay AI Descriptions",
    "402": "> Onsen Scenario #4",
    "403": "> Gacha Roullette #1",
    "404": "> Gacha Roullette #2",
    "407": "> Onsen Scenario #5",
    "408": "> Onsen Scenario #6",
    "409": "> Onsen Scenario #7",
    "410": "> Autoplay #8",
    "411": "> Champions Meeting Special Rules",
    "412": "> Onsen Scenario #8",
    "416": "> Strolls",
    "417": "> Island Scenario #5",
    "418": "> Island Scenario #6",
    "419": "> Island Scenario #7",
    "422": "> Onsen Scenario #9",
    "423": "> SiL Career Story Choices #1",
    "424": "> SiL Career Story Choices #2",
    "432": "> Onsen Scenario #10"
};
export default categories;
